export const SET_FLIGHT_TEXT_INPUT = 'SET_LOCATION_TEXT_INPUT';
export const SET_DEFAULT_INPUT = 'SET_DEFAULT_INPUT';
export const GET_FLIGHT_DATA = 'GET_FLIGHT_DATA';
export const LOADING_FLIGHT_DATA = 'LOADING_FLIGHT_DATA';
export const LOADED_FLIGHT_DATA = 'LOADED_FLIGHT_DATA';
export const ERROR_FLIGHT_DATA = 'ERROR_FLIGHT_DATA';
export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS';
export const SET_LOGOUT_STATUS = 'SET_LOGOUT_STATUS';
export const SET_USERNAME_STATUS = 'SET_USERNAME_STATUS';
export const GET_LOGIN_DATA = 'GET_LOGIN_DATA';

// export const alertConstants = {
//     SUCCESS: 'ALERT_SUCCESS',
//     ERROR: 'ALERT_ERROR',
//     CLEAR: 'ALERT_CLEAR'
// };
// export const userConstants = {
//     REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
//     REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
//     REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

//     LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
//     LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
//     LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    
//     LOGOUT: 'USERS_LOGOUT',

//     GETALL_REQUEST: 'USERS_GETALL_REQUEST',
//     GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
//     GETALL_FAILURE: 'USERS_GETALL_FAILURE',

//     DELETE_REQUEST: 'USERS_DELETE_REQUEST',
//     DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
//     DELETE_FAILURE: 'USERS_DELETE_FAILURE'    
// };